services:
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: locallink_dev
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
