services:
  # PostgreSQL with PostGIS
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: locallink_api_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - locallink_network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - locallink_network

  # Phoenix API Server
  api:
    build: .
    environment:
      MIX_ENV: dev
      DATABASE_URL: ecto://postgres:postgres@postgres:5432/locallink_api_dev
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY_BASE: your-very-long-secret-key-base-for-development-make-it-64-characters
      GUARDIAN_SECRET_KEY: your-development-secret-key-make-it-very-long-and-secure-for-jwt
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/_build
      - /app/deps
    networks:
      - locallink_network
    command: >
      sh -c "
        mix deps.get &&
        mix ecto.setup &&
        mix phx.server
      "

  # Optional: Adminer for database management
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - locallink_network

volumes:
  postgres_data:
  redis_data:

networks:
  locallink_network:
    driver: bridge