services:
  db:
    image: postgis/postgis:13-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: locallink_api_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6
    # ports:
    #   - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: mix phx.server
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/locallink_api_dev
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY_BASE: your_secret_key_base
      GUARDIAN_SECRET_KEY: your_guardian_secret
      # остальные переменные из runtime.exs

volumes:
  db_data:
