version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: locallink_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: mix phx.server
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      DATABASE_URL: ecto://postgres:postgres@db/locallink_dev
    depends_on:
      - db
    volumes:
      - .:/app
      - deps:/app/deps
      - _build:/app/_build

volumes:
  db_data:
  deps:
  _build:
